# #####################################################################
# Automatically generated by qmake (2.01a) Wed Feb 25 00:18:28 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clock.h \
    settingsdlg.h
SOURCES += clock.cpp \
    main.cpp \
    settingsdlg.cpp
FORMS += settings.ui

RESOURCES += bc_resources.qrc

CONFIG += qt debug
